#!/bin/bash

# exit if any command fails
set -e

# change to the _data directory in the parent
cd "$(dirname "$0")/../_data"

# uncompress the ua_expenses.csv.gz file
gzip -dcf ua_expenses.csv.gz > ua_expenses.csv
